name: uformer-aio3
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - pip
  - pytest>=7.0.0
  - conda-forge::einops>=0.7.0
  - conda-forge::pillow>=9.0.0
  - pip:
      - --index-url https://pypi.org/simple
      - wandb==0.25.1
